version: '3.8'

services:

  ros-mujoco:
    build:
      dockerfile: Dockerfile
      context: ./
    # networks:
    #   - ros
    
    container_name: ros-mujoco
    stdin_open: true # docker run -i
    tty: true # docker run -t 
    privileged: true

    environment:
      - 'DISPLAY=:0'
      - 'QT_X11_NO_MITSHM=1'
      - 'XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir'
      - 'PULSE_SERVER=/mnt/wslg/PulseServer'
      - 'WAYLAND_DISPLAY=wayland-0'

    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg

      - './src/:/root/workdir/src/'