# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    google_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    google_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

google_arm_controller:
  ros__parameters:
    joints:
      - joint_torso
      - joint_shoulder
      - joint_bicep
      - joint_elbow
      - joint_forearm
      - joint_wrist
      - joint_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

google_hand_controller:
  ros__parameters:
    joint: joint_finger_left

diff_drive_controller:
  ros__parameters:
    left_wheel_names : ["joint_left_wheel"]
    right_wheel_names : ["joint_right_wheel"]

    wheel_separation: 0.36566
    # wheels_per_side: 1
    wheel_radius: 0.0185
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0