# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    google_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    google_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

google_arm_controller:
  ros__parameters:
    joints:
      - joint_torso
      - joint_shoulder
      - joint_bicep
      - joint_elbow
      - joint_forearm
      - joint_wrist
      - joint_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

google_hand_controller:
  ros__parameters:
    joint: joint_finger_left

diff_drive_controller:
  ros__parameters:
    left_wheel_names : ["joint_left_wheel"]
    right_wheel_names : ["joint_right_wheel"]
    wheel_separation: 0.36566
    wheels_per_side: 1
    wheel_radius: 0.0185
    base_frame_id: "base_link"