# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    google_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    google_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

google_arm_controller:
  ros__parameters:
    joints:
      - joint_torso
      - joint_shoulder
      - joint_bicep
      - joint_elbow
      - joint_forearm
      - joint_wrist
      - joint_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
google_hand_controller:
  ros__parameters:
    joint: joint_finger_left